### ISSUE TITLE
Tab title not on Center

### ISSUE THREAD

**Issue by YashBhondave** [FirefoxCSSThemers/WhiteSur-FirefoxTheme#6]
Some Tab Title are not center aligned. I noticed this when I open .pdf files[
![Screenshot (68)](https://user-images.githubusercontent.com/85744364/128638264-b5e5744b-746c-460a-b5f5-1149cfff66fc.png)
![Screenshot (67)](https://user-images.githubusercontent.com/85744364/128638266-5395597d-ce2b-4897-bebe-5a77fba27348.png)
](url)

**Comment by AlfarexGuy2019** [comment]
Taken care of 😄. Hopefully be fixed in the next beta.
