### ISSUE TITLE
[GLITCH] Almost unusable after latest update.

### ISSUE THREAD

**Issue by satanphobia** [FirefoxCSSThemers/WhiteSur-FirefoxTheme#7]
I did a post on [Reddit](https://www.reddit.com/r/FirefoxCSS/comments/tdfvhh/whitesur_firefox_theme_all_glitched_up_after/) about this a few minutes ago, and seems like the right path is to report this glitch here too.

_Saying it again_, seems like some things broke after the latest beta update(_99.0b2_), **maybe** this glitch is on stable too.

List of things that broke are:

- All three window control buttons are all glitched up.
- The order is now back to default (minimize, maximize and close. it was inverted before the update).
- The tab bar now got a darker spacing and don't auto-hide when there's a single tab anymore.
- The favorite icon is stretched, and the back and forward buttons are just gone.

Plus some minor glitches that can be noticed on the screenshot attached.
![firefox_GYQIIHtpxc](https://user-images.githubusercontent.com/69485578/158082799-206bf389-70e0-4752-aaba-09c8ea14b4c1.png)
Specs are: _Windows 11 Laptop, using MyDockFinder for a Mac Style, Firefox Beta 99.0b2._

**Please**, fix this as soon as possible, as I love this theme a lot.
Thanks in advance.

**Comment by AdamXweb** [comment]
Hi, it seems this theme bundles my theme inside it.
There are multiple fixes released since the version bundled that you can find here:
https://github.com/AdamXweb/WhiteSurFirefoxThemeMacOS/releases/tag/v1.4.2
Note, the file under `chrome/WhiteSur/parts/windows.css` has the update you're looking for
