### ISSUE TITLE
Attribution?

### ISSUE THREAD

**Issue by AdamXweb** [FirefoxCSSThemers/WhiteSur-FirefoxTheme#8]
Hi,

I understand my themeis included in your release.
The theme has a MIT License associated with it.
Please update your contributions list to include credit for windows and other adaptions from my theme:
https://github.com/AdamXweb/WhiteSurFirefoxThemeMacOS/

Thanks
AdamXweb

**Comment by AlfarexGuy2019** [comment]
Hi @AdamXweb ,
Thank you for pointing that out. It's truly our fault we weren't aware of the fact, but we'll credit your theme, after all your work deserves to be seen. Very sorry for any inconvenience caused.
Alfarex.
